Storage flag
adobe/alloy pull request #1064
Opened 2023-10-24 05:34 UTC by shandilya3

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [X] I have made any necessary test changes and all tests pass.
- [X] I have run the Sandbox successfully.

2023-10-24 18:40 UTC, carterworks commented on src/components/DecisioningEngine/index.js
> +        if (personalizationStorageEnabled) {
Why is the storaged created inside the `onComponentsRegistered()` callback?

2023-10-24 19:02 UTC, jasonwaters requested changes

2023-10-24 19:02 UTC, jasonwaters commented on src/components/DecisioningEngine/index.js
> +                storage.persistent.clear();
If a customer sets `personalizationStorageEnabled` to false at some point, local storage should also be cleared.  That way customer's won't disable it and wonder why they still see an entry in local storage.

2023-10-24 19:02 UTC, jasonwaters commented on src/components/DecisioningEngine/index.js
> +          consent
I think it's fine to have `.awaitConsent()` here in the `index.js` file.  But I wonder if it makes sense to move the listener within `eventRegistry` instead? 🤔 There are pros/cons.

2023-10-24 19:43 UTC, carterworks commented on src/components/DecisioningEngine/createEventContext.js
> +    currentEventRegistry = eventRegistry;
If a new event registry is set, should it copy over the events from the previous registry?

2023-10-25 18:04 UTC, jasonwaters reviewed
looks great @shandilya3 !  Just one suggestion.

2023-10-25 18:04 UTC, jasonwaters commented on src/components/DecisioningEngine/createEventRegistry.js
> +  const setStorage = newStorage => {
I think it's redundant to have both `updateStorage` and `setStorage` functions.

I recommend removing this version of `setStorage` and renaming the `updateStorage` method above to `setStorage`.  Implementation of `setStorage` can be modified to accept `newStorage`  for example...

```js
  let currentStorage;
  let restore;
  let save;
  let events;

  const setStorage = newStorage => {
    currentStorage = newStorage;

    restore = createRestoreStorage(currentStorage, STORAGE_KEY);
    save = createSaveStorage(
      currentStorage,
      STORAGE_KEY,
      createEventPruner(MAX_EVENT_RECORDS, RETENTION_PERIOD)
    );
    events = restore({});
  };

  setStorage(storage);
```

2023-10-25 20:41 UTC, jasonwaters approved these changes

2023-10-25 22:44 UTC, merged