Return regionId in getIdentity calls
adobe/alloy pull request #671
Opened 2021-02-25 00:59 UTC by jonsnyder

## Description

Konductor returns edge information in the header "x-adobe-edge". This change parses this header and exposes the regionId as part of the response to the getIdentity command.

## Related Issue

https://jira.corp.adobe.com/browse/PDCL-4243

## Motivation and Context

Some customers need the regionId to call other services.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

2021-02-25 17:31 UTC, jfkhoury approved these changes
💡

2021-02-25 21:04 UTC, Aaronius requested changes
Love it. I'd like for the change I requested to be made, but let me know if you disagree so we can talk through it.

2021-02-25 21:04 UTC, Aaronius commented on src/components/Identity/createComponent.js
> +        edge = assign(edge, response.getEdge());
Mind leaving a comment as to why we're using `assign` here?

2021-02-26 18:00 UTC, jfkhoury commented on src/core/edgeNetwork/injectSendEdgeNetworkRequest.js
> +      .then(({ parsedBody, getHeader }) => {
Love this change!!!

2021-02-26 18:46 UTC, Aaronius approved these changes

2021-02-26 18:47 UTC, Aaronius commented
Looks great Jon. I'd still like to see a comment on the `assign` in case that was forgotten (https://github.com/adobe/alloy/pull/671#discussion_r583184747). This looks good to go though.

2021-02-26 23:19 UTC, Aaronius commented on src/components/Identity/createComponent.js
>          edge = assign(edge, response.getEdge());
I don't care if you change this, but `edge = ` is unnecessary. `assign(edge, response.getEdge());` will suffice.

2021-02-26 23:52 UTC, merged