Vite AEP Web Sandbox
adobe/alloy pull request #786
Opened 2021-11-24 18:06 UTC by shammowla

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.

2021-11-30 18:16 UTC, jfkhoury commented on vite-sandbox/index.html
> +    <script src="https://cdn1.adoberesources.net/alloy/2.7.0/alloy.js" async></script>
Should we consider re-adding the `latest` folder to our CDN?

2021-11-30 18:17 UTC, jfkhoury commented on vite-sandbox/src/components/App.jsx
> +        <h1>Hello Vite + React!</h1>
Update title

2021-11-30 18:18 UTC, jfkhoury requested changes
Couple of comments and let's please add new lines everywhere.
Thanks.

2022-03-08 17:39 UTC, jonsnyder commented
This project is on the back-burner for now.

2022-03-08 17:39 UTC, closed without merging