Force GitHub Actions npm cache reset
adobe/alloy pull request #788
Opened 2021-12-03 15:01 UTC by XDex

## Description

After merging #783, functional tests failed on `main` branch, due to npm cache not being reset after adding a new dev dependency.
This PR adds a mechanism for incrementing npm cache key value in GA workflows, so that it could be reset and functional tests would use the latest npm cache.
See this [Cache Action issue](https://github.com/actions/cache/issues/2) for more context.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

2021-12-03 15:04 UTC, XDex commented
@jonsnyder Could you please take a quick look?
Thanks!

2021-12-08 16:02 UTC, ninaceban requested changes
Remove unnecessary spaces and add new lines at EOF where needed please.

2021-12-08 19:29 UTC, jonsnyder commented
@shammowla can you take a look? You are more familiar with these workflow files.

2021-12-09 21:56 UTC, XDex commented
> Remove unnecessary spaces and add new lines at EOF where needed please.

@ninaceban Not sure what you mean, the redundant spaces have been already cleaned up and newlines already added at EOF automatically by Idea in my commit, you've probably mixed up the before (red) and after (green) mods when reviewing..

2021-12-17 13:16 UTC, merged