Create test branch from release candidate
adobe/alloy pull request #798
Opened 2022-01-25 16:35 UTC by shammowla

The production test workflow are using automated tests provided by test branches created from tags. Updated workflow to create a test branch prior to release. 

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.

2022-01-25 17:30 UTC, jfkhoury commented
Thank you for the description!

2022-01-25 17:37 UTC, jfkhoury approved these changes
Looks good @shammowla but I will let Jon and Martin verify.

2022-01-26 22:27 UTC, jonsnyder requested changes
I see you found a workflow job to create the branch. This could work instead of the javascript changes I suggested, but you need to put it into the deployRelease workflow, and setup the dependencies correctly.

validate -> release -> createTestBranch -> record
________`---------->prerelease -----------/

2022-01-28 16:12 UTC, shammowla commented
@jonsnyder I moved the job to the deployRelease workflow.

2022-02-01 18:06 UTC, shammowla commented
@jonsnyder made the changes we discussed.

2022-02-02 00:09 UTC, jonsnyder requested changes

2022-02-02 00:09 UTC, jonsnyder commented on .github/workflows/deployRelease.yml
> +    needs: validate
This should be `needs: release`, and then move this job below release for consistency.

2022-02-03 16:38 UTC, merged