TNT-43687 Sandbox - support merged metric propositions in client-side A4T
adobe/alloy pull request #849
Opened 2022-04-08 12:37 UTC by XDex

## Description

Support merged metric propositions on the client-side A4T sample page in the sandbox.

## Related Issue

https://jira.corp.adobe.com/browse/TNT-43687

## Motivation and Context

Support merged metric propositions on the client-side A4T sample page in the sandbox.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

2022-04-11 17:41 UTC, 5amfung requested changes

2022-04-11 17:41 UTC, 5amfung commented on sandbox/src/analyticsTokenHandler.js
> +export const getDisplayAnalyticsToken = proposition => {
`getAnalyticsTokenForDisplay`

2022-04-11 17:41 UTC, 5amfung commented on sandbox/public/onBeforeEventSentHelper.js
> +function getClickAnalyticsToken(proposition) {
Just nitpicking and suggesting `getAnalyticsTokenForClick`, but I would also be fine if name is not changed.

2022-04-11 17:41 UTC, 5amfung approved these changes

2022-04-20 22:13 UTC, jonsnyder approved these changes

2022-04-20 22:14 UTC, merged