PDCL-1305: Create uniqueItems() validator for array validation
adobe/alloy pull request #889
Opened 2022-07-18 20:52 UTC by adityaguruprasad

## Description
Creating a uniqueItems() validator for array validation

Use-cases: getIdentity and decisionScope
- getIdentity: array validator validates that edge cases such as ["ECID", "ECID"] aren't allowed to pass
- decisionScope: array validator validates that decisionScope array values cannot contain duplicates

## Related Issue
Currently no array unique items validator in place to ensure that duplicate values aren't passed on command through getIdentity or decisionScope.

## Motivation and Context
Ensuring that all array values passed in getIdentity and decisionScope are unique.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

2022-07-19 15:31 UTC, jonsnyder requested changes

2022-07-19 15:31 UTC, jonsnyder commented on src/utils/isUnique.js
> +export default value => new Set(value).size === Array(...value).length;
This doesn't work in Internet Explorer 11. That's why the tests are failing. `new Set(iterable)` is not supported, you can create a new set and add all the items to it.

2022-07-19 20:32 UTC, jonsnyder approved these changes

2022-07-22 16:02 UTC, jfkhoury commented on src/utils/isUnique.js
> +// new Set(value).size === Array(...value).length;
Let's get rid of this comment.

2022-07-22 16:02 UTC, jfkhoury commented on src/utils/isUnique.js
> +export default value => {
Should we rename `value` to `values`?

2022-07-22 16:03 UTC, jfkhoury commented on src/utils/validation/createUniqueItemsValidator.js
> +  // const values = [];
Let's get rid of this comment.

2022-07-22 16:03 UTC, jfkhoury approved these changes
Couple of quick comments, otherwise great stuff.

2022-07-22 23:14 UTC, merged